id: P005430
initial_creation_type: ocr
source_metadata:
  id: bdr:W21761
  title: བརྡ་སྤྲོད་གཞུང་ལ་འཇུག་པའི་ཉམས་སྣང་།
  author: ''
  volumes:
    14d7ffb211f148dfb3cd9fc22592e47f:
      image_group_id: I1PD28044
      title: ''
      volume_number: 1
      total_pages: 374
      base_file: v001.txt
